# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GithubActionsTest < Formula
  'include Language::Python::Virtualenv'

  desc "I test github actions here so i don't blow up my real projects. ignore this repo"
  homepage "https://github.com/justintime50/github-actions-test"
  url "https://github.com/justintime50/github-actions-test/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "792b068a8cfc19b3b78db9464dc872a08564cd6fcb9f273d2ec625a50d7662c2"

  depends_on "python@3.14"

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "github-archive \#{version}", shell_output("#{bin}/github-archive --version")
  end
end
