# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GithubActionsTest < Formula
  desc "I test github actions here so i don't blow up my real projects. ignore this repo"
  homepage "https://github.com/Justintime50/github-actions-test"
  url "https://github.com/Justintime50/github-actions-test/releases/download/v0.2.0/muffinscript.tar.gz"
  sha256 "b2b0c902c26d999d132aa4e1b9a7b2faeb62ee9b6de9585eb6591a6ad4bb5bf6"

  def install
    libexec.install "muffin"
    bin.install_symlink libexec/"muffin/muffin" => "muffin"
  end

  test do
    assert_match "Muffin", shell_output("#{bin}/muffin --version")
  end
end
