# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Muffinscript < Formula
  desc "Delectable little programming language"
  homepage "https://github.com/justintime50/muffinscript"
  url "https://github.com/justintime50/muffinscript/releases/download/v0.2.0/muffinscript.tar.gz"
  sha256 "2ee030dd30e52a0b98f06217de87a4da67346b067c0ebb9907828c09a3c51347"
  license "MIT"

  def install
    libexec.install "muffin"\nbin.install_symlink libexec/"muffin/muffin" => "muffin"
  end

  test do
    assert_match "Muffin", shell_output("#{bin}/muffin --version")
  end
end
